#!/usr/bin/env php
<?php

    $birthDate = '1984-08-01';
    include 'src/Dates/Birthdays.php';
    $days = new \SweetBrides\Dates\Birthdays($birthDate);
    $totalDays = $days->findTotalDays();
    $totalHours = $days->findTotalHours();
    $totalSecs = $days->findTotalSecs();
    echo "$birthDate : $totalSecs Seconds, $totalHours Hours, $totalDays Days\n";

?>
